### ISSUE TITLE
Cannot read raw data in Supporting Information in the AC article.

### ISSUE THREAD

**Issue by LipidAnalysis** [SLINGhub/LICAR#1]
I attemped to read "ac0c04565_si_003.xlsx (82.66 kb)" file in Supporting information in the AC article, but it failed with error "The length [1] of the 'names' attribute must be the same as the length [0] of the vector".

**Comment by bchacgt** [comment]
Hello, sorry for the late reply, I did not monitor this account for a while. If I understand correctly, you have trouble opening one of the supplementary excel file from the article, is that right? I have just tried on the Analytical Chemistry website and it worked fine. I could send you the file via email if you'd like.

**Comment by bchacgt** [comment]
Sorry for the late reply, I have not monitored the account for a while. Do you mean that you tried to import the xlsx file with LICAR? If so, it would work. Data from each lipid class must be imported as separate csv file. You can try to save individual sheets from "ac0c04565_si_003.xlsx" to .csv files and import these into LICAR.
If this i not what your problem was, please let us know exactly what you have done.

**Comment by bchacgt** [comment]
issuer did not reply after a while
